version: 2
updates:
  - package-ecosystem: maven
    target-branch: "main-dev"
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
      timezone: Etc/UCT
    reviewers:
      - "liga-oz"
      - "finkmanAtSap"
    open-pull-requests-limit: 10
